export const ROUTES = {
  HOME: '/dashboard',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  TRANSACTION: '/transaksi',
  LIST_MOTOR: '/list-motor',
  MOTOR_ON_GOING: '/on-going',
  SERVICE: '/service',
  REPORT: '/laporan',
  MANAGE_USER: '/kelola-user',
};
